// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhqubaclqiwczwxzvqyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocXViYWNscWl3Y3p3eHp2cXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODg4NzUsImV4cCI6MjA2ODk2NDg3NX0.gMFgEnSqZFGh6sz764Pz48VQW3qVwcGtu18uYS_pTWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});